import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { trpc } from "../utils/trpc";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Weakest Z-fighter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container flex flex-col items-center gap-16 h-screen p-4">
        <h1 className="text-5xl leading-normal font-extrabold text-gray-700">
          Who is the weakest
        </h1>
        <ul className="flex flex-row gap-16 justify-around items-center text-5xl">
          <li className="flex flex-col items-center gap-4 text-3xl font-semibold">
            <button>
              <Image
                width="250px"
                height="350px"
                src="https://cdn.myanimelist.net/images/characters/7/238175.jpg"
                alt=""
              />
              
            </button>
            <span>Name</span>
          </li>
          <li>
            <button>vs</button>
          </li>
          <li className="flex flex-col items-center gap-4 text-3xl font-semibold">
            <button>
              <Image
                width="250px"
                height="350px"
                src="https://cdn.myanimelist.net/images/characters/7/238175.jpg"
                alt=""
              />
            </button>
            <span>Name</span>
          </li>
        </ul>
        <div></div>
      </main>
    </>
  );
};

export default Home;
